# Generated by Django 4.0.4 on 2022-08-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_project_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
