# Generated by Django 4.0.4 on 2022-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_alter_project_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='people_assigned',
            field=models.ManyToManyField(blank=True, help_text='Who is working on this task?', null=True, to='ProjectManager.person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_groups',
            field=models.ManyToManyField(blank=True, help_text='What group does this task belong to?', null=True, to='ProjectManager.group_type'),
        ),
    ]
